<?php

namespace Gogole\MainBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EventEntityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventEntityRepository extends EntityRepository
{
}
