<<<<<<< HEAD
gogole_user:
    resource: "@GogoleUserBundle/Resources/config/routing.yml"
    prefix:   /

gogole_todo:
    resource: "@GogoleTodoBundle/Resources/config/routing.yml"
    prefix:   /

gogole_main:
    resource: "@GogoleMainBundle/Resources/config/routing.yml"
    prefix:   /
    
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
=======
gogole_categoriecontact:
    resource: "@GogoleContactBundle/Controller/"
    prefix:   /main/
    type:     annotation

gogole_societe:
    resource: "@GogoleContactBundle/Controller/"
    prefix:   /main/
    type:     annotation

gogole_contact:
    resource: "@GogoleContactBundle/Controller/"
    prefix:   /main/
    type:     annotation

gogole_todo:
    resource: "@GogoleTodoBundle/Resources/config/routing.yml"
    prefix:   /main/

gogole_tchat:
    resource: "@GogoleTchatBundle/Resources/config/routing.yml"
    prefix:   /main/

gogole_main:
    resource: "@GogoleMainBundle/Resources/config/routing.yml"
    prefix:   /main/

>>>>>>> upstream/master
