gogole_main_homepage:
    path:   /
    defaults: { _controller: GogoleTodoBundle:Todo:listeTache }

gogole_main_planningpage:
    path:   /calendar
    defaults: { _controller: GogoleMainBundle:Main:planning  }
