<?php

namespace Gogole\ContactBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * categorieContactRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class categorieContactRepository extends EntityRepository
{
}
