<?php

namespace Gogole\GestionStockBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * stockManagerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class stockManagerRepository extends EntityRepository
{
}
